<?xml version="1.0" encoding="utf-8"?>
<qroot>
<question>
<Title>Kubernetes authorization, only succesful after running hello-server</Title>
<Body>&lt;p&gt;I&#x27;ve been working on a python project with the goal to interact with Kubernetes. One of the problems I have run into is the authentication process. Similar to &lt;a href=&quot;https://stackoverflow.com/questions/50717812/google-cloud-natural-language-api-errorgoogle-auth-exceptions-defaultcredential&quot;&gt;this&lt;/a&gt; question I get the error&lt;/p&gt;&lt;blockquote&gt;  &lt;p&gt;google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see &lt;a href=&quot;https://cloud.google.com/docs/authentication/getting-started&quot; rel=&quot;nofollow noreferrer&quot;&gt;https://cloud.google.com/docs/authentication/getting-started&lt;/a&gt;&lt;/p&gt;&lt;/blockquote&gt;&lt;p&gt;I understand that this is probably due to the fact that I use pycharm. However, when I run it from the terminal, I get this error:&lt;/p&gt;&lt;blockquote&gt;  &lt;p&gt;kubernetes.client.rest.ApiException: (403)  Reason: Forbidden  HTTP response headers: HTTPHeaderDict({&#x27;Audit-Id&#x27;: &#x27;XXXXXXXXXXX&#x27;, &#x27;Content-Type&#x27;: &#x27;application/json&#x27;, &#x27;X-Content-Type-Options&#x27;: &#x27;nosniff&#x27;, &#x27;Date&#x27;: &#x27;XXXXXXXXXXXXXXXX&#x27;, &#x27;Content-Length&#x27;: &#x27;XXX&#x27;})  HTTP response body: {&quot;kind&quot;:&quot;Status&quot;,&quot;apiVersion&quot;:&quot;v1&quot;,&quot;metadata&quot;:{},&quot;status&quot;:&quot;Failure&quot;,&quot;message&quot;:&quot;deployments.extensions is forbidden: User \&quot;XXXXXXXXXXXXXXXXXXX\&quot; cannot create deployments.extensions in the namespace \&quot;default\&quot;: Required \&quot;container.deployments.create\&quot; permission.&quot;,&quot;reason&quot;:&quot;Forbidden&quot;,&quot;details&quot;:{&quot;group&quot;:&quot;extensions&quot;,&quot;kind&quot;:&quot;deployments&quot;},&quot;code&quot;:403}&lt;/p&gt;&lt;/blockquote&gt;&lt;p&gt;However, when I change my code from:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;os.system(f&quot;gcloud container clusters get-credentials {cluster_name} --zone {zone} --project {project}&quot;)&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;to&lt;/p&gt;&lt;pre&gt;&lt;code&gt;os.system(f&quot;gcloud container clusters get-credentials {cluster_name} --zone {zone} --project {project}&quot;)os.system(&quot;kubectl run hello-server --image gcr.io/google-samples/hello-app:1.0 --port 8080&quot;)os.system(&quot;kubectl delete deployments hello-server&quot;)&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;I can authenticate and all other functionality is exactly as it should be. I don&#x27;t understand why this is. I think it&#x27;s probably an indication something is wrong and would like to fix it before continuing. Does anybody know what is happening here, and how to fix it?&lt;/p&gt;</Body>
<Tags>python,authentication,kubernetes</Tags>
</question>
<answer>
<Body>&lt;p&gt;What about to use kubernetes client for python ?&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;https://github.com/kubernetes-client/python&quot; rel=&quot;nofollow noreferrer&quot;&gt;https://github.com/kubernetes-client/python&lt;/a&gt;&lt;/p&gt;&lt;p&gt;Check this example for remote cluster access:&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;https://github.com/kubernetes-client/python/blob/master/examples/remote_cluster.py&quot; rel=&quot;nofollow noreferrer&quot;&gt;https://github.com/kubernetes-client/python/blob/master/examples/remote_cluster.py&lt;/a&gt;&lt;/p&gt;</Body>
</answer>
<answer>
<Body>&lt;p&gt;From your error description I can see, that You are &lt;strong&gt;not&lt;/strong&gt; having problem with authentication but authorization to Kubernetes. These are two different things.&lt;/p&gt;&lt;p&gt;The error message you posted should be interpreted in following way: &lt;br&gt;&quot;&lt;em&gt;You are not authorized to perform &quot;create&quot; action on &quot;deployment&quot; object.&lt;/em&gt;&quot; &lt;/p&gt;&lt;p&gt;The mechanism that blocks your user access to specific operation on cluster resources is called RBAC - role-based access control (RBAC), which is built in GKE, and generally enabled in Kubernetes 1.6 onwards.&lt;/p&gt;&lt;p&gt;How to solve your problem:&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Grant your GCP user/GCP service account appropriate role.&lt;/li&gt;&lt;/ol&gt;&lt;p&gt;The queasiest way is to use one of predefined &lt;a href=&quot;https://cloud.google.com/kubernetes-engine/docs/how-to/iam&quot; rel=&quot;nofollow noreferrer&quot;&gt;Cloud AIM roles for Kubernetes clusters&lt;/a&gt;, e.g.  &quot;roles/container.admin&quot;, which will be mapped automatically to ClusterRole (cluster-admin). Please keep in mind to apply &quot;principle of least privilege&quot;, especially for production clusters.&lt;/p&gt;&lt;ol start=&quot;2&quot;&gt;&lt;li&gt;&lt;p&gt;If you created a GCP Service Account in step #1&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;p&gt;download its key in JSON format&lt;/p&gt;&lt;/li&gt;&lt;li&gt;&lt;p&gt;Provide authentication credentials to your application code by setting the environment variable GOOGLE_APPLICATION_CREDENTIALS &lt;br&gt;&lt;br&gt;&lt;/p&gt;&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;I&#x27;m setting it up directly inside my python app:&lt;/p&gt;&lt;/li&gt;&lt;/ol&gt;&lt;blockquote&gt;  &lt;p&gt;import os&lt;br&gt;  os.environ[&quot;GOOGLE_APPLICATION_CREDENTIALS&quot;]=&#x27;gke-admin-svc-key.json&#x27;&lt;/p&gt;&lt;/blockquote&gt;&lt;p&gt;From now on you should be able to interact with your cluster from outside, in context of GCP service account, which should be reflected in audit logs:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;authenticationInfo: {   principalEmail:  &quot;&amp;lt;id_of_your_svc_account&amp;gt;&quot;      }  authorizationInfo: [   0: {    granted:  true         permission:  &quot;io.k8s.core.v1.pods.list&quot;         resource:  &quot;core/v1/pods&quot;        }  ]&lt;/code&gt;&lt;/pre&gt;</Body>
</answer>
</qroot>
